import type {BeatEvent} from '../audio/AudioEngine';
import type {Track} from '../audio/TrackDefinitions';
import type {ResonanceEngine,Node} from '../game/ResonanceEngine';
import type {RuntimeConfig} from '../config/constants';

export class Renderer {
  private ctx:CanvasRenderingContext2D;w=0;h=0;dpr=1;private eighth=0;private kick=0;private snare=0;private hat=0;private bar=0;private bass=0;private arp=0;private arpPitch=0;private melody=0;private melodyPitch=0;private responsePulse=0;private responseVariation=false;private memoryPulse=0;private memoryNotes:number[]=[];private beatStep=0;private cameraX=0;private cameraY=0;private cameraScale=1;private cameraAngle=0;private fps=60;private lastFrame=0;private quality=1;
  constructor(private canvas:HTMLCanvasElement,private cfg:RuntimeConfig){this.ctx=canvas.getContext('2d')!;this.resize();}
  resize=()=>{const r=this.canvas.getBoundingClientRect();this.dpr=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.canvas.width=Math.floor(this.w*this.dpr);this.canvas.height=Math.floor(this.h*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);};
  beat(event:BeatEvent){this.beatStep=event.step;this.eighth=1;this.hat=event.hat?1:0;this.kick=event.kick?1:0;this.snare=event.snare?1:0;this.bar=event.bar?1:0;this.bass=event.bass?1:0;this.arp=event.arp?1:0;this.arpPitch=event.arpNote;this.melody=1;this.melodyPitch=event.melody;if(event.response){this.responsePulse=1;this.responseVariation=event.response==='variation';}}
  memory(notes:number[]){this.memoryNotes=[...notes];this.memoryPulse=1;}
  focus(x:number,y:number,strength:number){this.cameraX+=(x-this.w/2)*.006*strength;this.cameraY+=(y-this.h/2)*.006*strength;}
  screenToWorld(x:number,y:number){const cx=this.w/2,cy=this.h/2,dx=x-cx-this.cameraX,dy=y-cy-this.cameraY,co=Math.cos(-this.cameraAngle),si=Math.sin(-this.cameraAngle);return{x:(dx*co-dy*si)/this.cameraScale+cx,y:(dx*si+dy*co)/this.cameraScale+cy};}
  draw(now:number,e:ResonanceEngine,t:Track){this.updateQuality(now);const c=this.ctx,cx=this.w/2,cy=this.h/2,streak=e.sync.streak,level=e.transitionLevel;this.decay();const trance=level>=2,resonance=level>=3,breath=Math.sin(now*.0018)*level*.0025;this.cameraScale=1+level*this.cfg.cameraZoom*.34+e.transitionPulse*.012+breath-this.kick*this.cfg.cameraZoom*.55;this.cameraAngle=trance?Math.sin(now*.00028)*this.cfg.cameraRotation:0;this.cameraX*=.88;this.cameraY*=.88;
    c.save();c.fillStyle=t.colors.bg;c.fillRect(0,0,this.w,this.h);this.background(c,now,t,e,cx,cy);c.translate(cx+this.cameraX,cy+this.cameraY);c.rotate(this.cameraAngle);c.scale(this.cameraScale,this.cameraScale);c.translate(-cx,-cy);c.globalCompositeOperation='lighter';
    if(e.state==='idle'||e.state==='rebirth')this.seed(c,now,e,t,cx,cy);
    if(e.state==='active'||e.state==='prelude')this.active(c,now,e,t,cx,cy,streak,e.state==='prelude'?Math.max(2,level):level,resonance||e.state==='prelude');
    if(e.state==='finale'||e.state==='whiteout')this.finale(c,now,e,t,cx,cy);
    for(const p of e.particles){c.globalAlpha=p.life*(this.quality<1?.72:1);c.fillStyle=t.colors.particle;c.beginPath();c.arc(p.x,p.y,p.size*p.life,0,Math.PI*2);c.fill();}c.restore();}
  private updateQuality(now:number){if(this.lastFrame){const instantaneous=1000/Math.max(1,now-this.lastFrame);this.fps=this.fps*.96+instantaneous*.04;if(this.fps<43)this.quality=.55;else if(this.fps>53)this.quality=1;}this.lastFrame=now;}
  private decay(){this.eighth*=.78;this.kick*=.76;this.snare*=.72;this.hat*=.58;this.bar*=.75;this.bass*=.86;this.arp*=.68;this.melody*=.8;this.responsePulse*=.78;this.memoryPulse*=.94;}
  private background(c:CanvasRenderingContext2D,now:number,t:Track,e:ResonanceEngine,cx:number,cy:number){const drift=Math.sin(now*.00035)*30*this.bass,g=c.createRadialGradient(cx+drift,cy-drift*.3,10,cx,cy,Math.hypot(this.w,this.h)*.65);g.addColorStop(0,this.alphaColor(t.colors.primary,.055+this.eighth*this.cfg.beatPulse+e.transitionLevel*.012));g.addColorStop(1,t.colors.bg);c.globalAlpha=1;c.fillStyle=g;c.fillRect(0,0,this.w,this.h);if(this.kick){c.globalAlpha=.035*this.kick;c.fillStyle='#000';c.fillRect(0,0,this.w,this.h);}if(this.snare){c.globalAlpha=.045*this.snare;c.fillStyle=t.colors.secondary;c.fillRect(0,cy-this.h*.12,this.w,this.h*.24);}if(this.eighth){c.globalAlpha=.035*this.eighth;c.strokeStyle=t.colors.primary;c.lineWidth=.7;c.beginPath();c.arc(cx,cy,Math.max(this.w,this.h)*(.58-.08*this.eighth),0,Math.PI*2);c.stroke();}}
  private seed(c:CanvasRenderingContext2D,now:number,e:ResonanceEngine,t:Track,cx:number,cy:number){const appear=e.state==='rebirth'?Math.min(1,(now-e.rebirthStart)/900):1,p=.5+.5*Math.sin(now*.003);c.fillStyle=t.colors.secondary;c.globalAlpha=(.45+.5*p)*appear;c.beginPath();c.arc(cx,cy,3+5*p,0,Math.PI*2);c.fill();c.globalAlpha=.1*appear;c.beginPath();c.arc(cx,cy,20+10*p,0,Math.PI*2);c.fill();}
  private active(c:CanvasRenderingContext2D,now:number,e:ResonanceEngine,t:Track,cx:number,cy:number,streak:number,level:number,resonance:boolean){
    if(level>0)this.connections(c,e.nodes,t,.045+level*.035+this.bar*.12,resonance?Math.min(45,e.nodes.length*4):e.nodes.length+4);
    if(this.snare)this.connections(c,e.nodes,t,.2*this.snare,Math.min(20,e.nodes.length*2));
    if(this.kick){c.globalAlpha=.13*this.kick;c.strokeStyle=t.colors.primary;c.lineWidth=1+this.kick;c.beginPath();c.arc(cx,cy,12+42*(1-this.kick),0,Math.PI*2);c.stroke();}
    for(const w of e.waves){const edge=Math.max(0,1-w.r/(Math.hypot(this.w,this.h)*.78)),fresh=w.alpha*w.alpha,alpha=this.cfg.waveOpacity*fresh*edge*(w.generation?.65:1);if(alpha<.01)continue;c.globalAlpha=alpha;c.strokeStyle=t.colors.primary;c.lineWidth=(.4+this.cfg.waveWidth*fresh*w.power)*(1+this.bass*.28);this.wavePath(c,w.x,w.y,w.r,resonance?8:level>=2?12:0,now);c.stroke();if(this.arp&&this.quality===1){const a=now*.004+w.r*.02;c.globalAlpha=alpha*.9*this.arp;c.fillStyle=t.colors.secondary;c.beginPath();c.arc(w.x+Math.cos(a)*w.r,w.y+Math.sin(a)*w.r,1.6,0,Math.PI*2);c.fill();}}
    for(const contact of e.contacts){const k=contact.life,boost=contact.synced?2:1;c.strokeStyle=t.colors.secondary;c.globalAlpha=k*.5*boost;c.lineWidth=.7+1.6*k*boost;c.beginPath();c.arc(contact.x,contact.y,8+(1-k)*28*boost,0,Math.PI*2);c.stroke();if(contact.synced){c.globalAlpha=k*.22;c.lineWidth=.65;c.beginPath();c.moveTo(contact.fromX,contact.fromY);c.lineTo(contact.x,contact.y);c.stroke();const u=1-k;c.fillStyle=t.colors.secondary;c.globalAlpha=k*.85;c.beginPath();c.arc(contact.fromX+(contact.x-contact.fromX)*u,contact.fromY+(contact.y-contact.fromY)*u,2.2,0,Math.PI*2);c.fill();}c.globalAlpha=k*.38*boost;c.beginPath();c.moveTo(contact.x-contact.dx*4,contact.y-contact.dy*4);c.lineTo(contact.x+contact.dx*(22+30*(1-k))*boost,contact.y+contact.dy*(22+30*(1-k))*boost);c.stroke();}
    const melodyTarget=e.nodes.reduce<Node|undefined>((best,n)=>!best||Math.abs(n.note-this.melodyPitch)<Math.abs(best.note-this.melodyPitch)?n:best,undefined);for(const n of e.nodes)this.node(c,now,n,t,n===melodyTarget,level);
    if(this.memoryPulse>.02&&e.nodes.length>1){c.strokeStyle=t.colors.secondary;c.lineWidth=.8+this.memoryPulse;c.globalAlpha=this.memoryPulse*.28;c.beginPath();this.memoryNotes.forEach((note,i)=>{const n=e.nodes.reduce((a,b)=>Math.abs(a.note-note)<Math.abs(b.note-note)?a:b),x=n.x,y=n.y;i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();}
    if(e.transitionPulse>.02){c.globalAlpha=e.transitionPulse*.28;c.strokeStyle=t.colors.secondary;c.lineWidth=1.2+level;c.beginPath();c.arc(cx,cy,30+(1-e.transitionPulse)*Math.min(this.w,this.h)*.48,0,Math.PI*2);c.stroke();}
    if(this.arp&&e.nodes.length>1){const a=e.nodes.reduce((best,n)=>Math.abs(n.note-this.arpPitch)<Math.abs(best.note-this.arpPitch)?n:best),index=e.nodes.indexOf(a),b=e.nodes[(index+1)%e.nodes.length],u=1-this.arp;c.fillStyle=t.colors.secondary;c.globalAlpha=this.arp*.8;c.beginPath();c.arc(a.x+(b.x-a.x)*u,a.y+(b.y-a.y)*u,2,0,Math.PI*2);c.fill();}
  }
  private node(c:CanvasRenderingContext2D,now:number,n:Node,t:Track,melodyTarget:boolean,level:number){const breath=.5+.5*Math.sin(now*.0024+n.id),anticipate=n.anticipation,beatGrow=this.eighth*.018+this.kick*.055+this.bar*.04,response=melodyTarget?this.responsePulse:0,size=(2.2+breath*.45+n.pulse*4+n.hitFlash*5+response*4)*(1-anticipate*.12)*(1+beatGrow+level*.025);c.fillStyle=this.responseVariation&&response?t.colors.primary:t.colors.secondary;c.globalAlpha=.28+n.life*.35+anticipate*.25+(melodyTarget?this.melody*.4+response*.3:0);c.beginPath();c.arc(n.x,n.y,size,0,Math.PI*2);c.fill();c.globalAlpha=.055+anticipate*.11+n.hitFlash*.2+response*.18;c.beginPath();c.arc(n.x,n.y,11+breath*4+n.hitFlash*13+response*10,0,Math.PI*2);c.fill();if(n.y<this.h*.33){c.globalAlpha=.08+response*.18;c.lineWidth=.5;c.strokeStyle=t.colors.secondary;c.beginPath();c.arc(n.x,n.y,15+breath*3,0,Math.PI*2);c.stroke();}if(this.hat>.15){const a=now*.006+n.id;c.globalAlpha=this.hat*.22;c.beginPath();c.arc(n.x+Math.cos(a)*9,n.y+Math.sin(a)*9,1,0,Math.PI*2);c.fill();}}
  private connections(c:CanvasRenderingContext2D,nodes:Node[],t:Track,alpha:number,max:number){if(nodes.length<2)return;c.strokeStyle=t.colors.primary;c.lineWidth=.55;c.globalAlpha=alpha;let drawn=0;for(let gap=1;gap<nodes.length&&drawn<max;gap++)for(let i=0;i<nodes.length&&drawn<max;i++){const a=nodes[i],b=nodes[(i+gap)%nodes.length];c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();drawn++;}}
  private finale(c:CanvasRenderingContext2D,now:number,e:ResonanceEngine,t:Track,cx:number,cy:number){const elapsed=now-e.finaleStart,gatherEnd=this.cfg.finaleGather,structureEnd=gatherEnd+this.cfg.finaleStructure,expandEnd=structureEnd+this.cfg.finaleExpand,gather=Math.min(1,elapsed/gatherEnd),structure=Math.min(1,Math.max(0,elapsed-gatherEnd)/this.cfg.finaleStructure),expand=Math.min(1,Math.max(0,elapsed-structureEnd)/this.cfg.finaleExpand),resolve=Math.max(0,(elapsed-expandEnd+900)/900),diag=Math.hypot(this.w,this.h),source=e.nodes.length>2?e.nodes:[{x:cx-40,y:cy+25},{x:cx+45,y:cy+30},{x:cx,y:cy-50}] as Node[],pts=source.map(p=>({x:p.x+(cx-p.x)*gather*.22,y:p.y+(cy-p.y)*gather*.22}));
    for(const wave of e.waves){c.globalAlpha=wave.alpha*(1-gather)*.35;c.strokeStyle=t.colors.primary;c.lineWidth=.6+wave.power;c.beginPath();c.arc(wave.x,wave.y,wave.r+elapsed*.012,0,Math.PI*2);c.stroke();}
    const mainAlpha=.25+.65*Math.min(1,structure+expand)-resolve*.2;c.strokeStyle=t.colors.secondary;c.lineJoin='round';c.globalAlpha=mainAlpha;c.lineWidth=1.8+this.kick*2.2;this.polygon(c,pts);c.stroke();for(const p of pts){c.globalAlpha=.35+this.melody*.45;c.fillStyle=t.colors.secondary;c.beginPath();c.arc(p.x,p.y,2.5+this.melody*2,0,Math.PI*2);c.fill();}
    if(structure>0){c.lineWidth=.75+this.snare*.55;c.globalAlpha=(.08+.32*structure)*(1-resolve*.75);let lines=0;for(let gap=2;gap<pts.length&&lines<this.cfg.structureLines;gap++)for(let i=0;i<pts.length&&lines<this.cfg.structureLines;i++){const a=pts[i],b=pts[(i+gap)%pts.length];c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();lines++;}}
    if(expand>0){const copies=Math.min(this.cfg.mainLines,Math.max(2,Math.round(2+expand*this.cfg.mainLines))),baseScale=1+expand*4.8;for(let copy=0;copy<copies;copy++){const a=Math.PI*2*copy/copies+now*.00012,scale=baseScale*(.48+copy/copies*.6);c.save();c.translate(cx,cy);c.rotate(a);c.scale(copy%2?-scale:scale,scale);c.translate(-cx,-cy);c.globalAlpha=(.04+.18*expand)*(1-resolve*.85);c.lineWidth=.45/Math.max(1,scale);this.polygon(c,pts);c.stroke();c.restore();}}
    const echoes=Math.round(this.cfg.echoLines*this.quality*expand*(1-resolve));for(let i=0;i<echoes;i++){const a=Math.PI*2*i/Math.max(1,echoes)+now*.0002,r=diag*(.18+.75*expand)*(1+.08*Math.sin(i*2.1));c.globalAlpha=.025+.055*this.hat;c.lineWidth=.35;c.beginPath();c.moveTo(cx+Math.cos(a)*r*.2,cy+Math.sin(a)*r*.2);c.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);c.stroke();}
    if(resolve>0){c.globalAlpha=Math.min(.65,resolve*.45+.2*this.kick);c.fillStyle=t.colors.secondary;c.beginPath();c.arc(cx,cy,diag*.72*resolve,0,Math.PI*2);c.fill();}}
  private polygon(c:CanvasRenderingContext2D,pts:{x:number;y:number}[]){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();}
  private wavePath(c:CanvasRenderingContext2D,x:number,y:number,r:number,sides:number,now:number){c.beginPath();if(!sides){c.arc(x,y,r,0,Math.PI*2);return;}for(let i=0;i<=sides;i++){const a=Math.PI*2*i/sides+now*.00008,rr=r*(1+.018*Math.sin(i*2+now*.003)),px=x+Math.cos(a)*rr,py=y+Math.sin(a)*rr;i?c.lineTo(px,py):c.moveTo(px,py);}c.closePath();}
  private alphaColor(hex:string,alpha:number){const value=hex.replace('#',''),n=parseInt(value.length===3?value.split('').map(x=>x+x).join(''):value,16);return`rgba(${n>>16},${n>>8&255},${n&255},${alpha})`;}
}
