import type {Track} from './TrackDefinitions';

export type MelodyMotif={notes:number[];score:number;createdBar:number;uses:number};
export type ArpeggioMotif={notes:number[];score:number;createdAt:number};
export interface FinaleCompositionSnapshot {primaryMelodyMotif:number[];secondaryMelodyMotif?:number[];primaryArpeggioMotif:number[];tapDensity:number;averageTapY:number;averageTapX:number;hiHatDensity:number;kickVariation:number;snareTone:number;longestSyncStreak:number;totalSyncCount:number;nodePositions:Array<{x:number;y:number;note:number}>;}
export interface CompositionState {tapDensity:number;averageTapInterval:number;averageTapX:number;averageTapY:number;kickIntensity:number;kickVariation:number;snareTone:number;snareFillLevel:number;hiHatDensity:number;hiHatOpenAmount:number;melodyNotes:number[];melodyCursor:number;arpeggioNotes:number[];arpeggioCursor:number;syncStreak:number;compositionEnergy:number;currentMelodyNote:number;nextQuantizedBeat:number;rememberedMotifs:MelodyMotif[];arpeggioMotifs:ArpeggioMotif[];longestSyncStreak:number;totalSyncCount:number;selectedPrimaryMotif:number[];selectedSecondaryMotif:number[];finaleSnapshot?:FinaleCompositionSnapshot;}
type QueuedMelody={note:number;synced:boolean};type Response={bar:number;notes:number[];variation:boolean};
const NOTE_MAPS=[[0,2,4,5,7],[0,1,3,4,6],[0,2,3,5,7],[0,2,4,6,7],[0,2,4,5,7]];
export class CompositionEngine {
  state:CompositionState=this.createState();private taps:{at:number;x:number;y:number}[]=[];private melodyQueue:QueuedMelody[]=[];private currentBarNotes:number[]=[];private barMaxSync=0;private responses:Response[]=[];private contactBuffer:{note:number;at:number;synced:boolean}[]=[];private frozen?:CompositionState;
  reset(){this.state=this.createState();this.taps=[];this.melodyQueue=[];this.currentBarNotes=[];this.responses=[];this.contactBuffer=[];this.frozen=undefined;}
  update(now:number,dt:number,syncStreak:number){this.taps=this.taps.filter(t=>now-t.at<=4000);if(this.contactBuffer.length&&now-this.contactBuffer.at(-1)!.at>900)this.finalizeArpeggio();const raw=this.taps.length/4,target=raw<.65?0:raw<1.55?.5:1,k=1-Math.exp(-dt/650);this.state.tapDensity+=(raw-this.state.tapDensity)*k;this.state.hiHatDensity+=(target-this.state.hiHatDensity)*k;this.state.syncStreak=syncStreak;this.state.longestSyncStreak=Math.max(this.state.longestSyncStreak,syncStreak);this.state.compositionEnergy=Math.min(1,this.state.tapDensity*.25+syncStreak*.08+this.state.rememberedMotifs.length*.12+this.state.arpeggioMotifs.length*.08);if(this.taps.length>1){const intervals=this.taps.slice(1).map((t,i)=>t.at-this.taps[i].at);this.state.averageTapInterval=intervals.reduce((a,b)=>a+b,0)/intervals.length;}}
  recordTap(track:Track,x:number,y:number,synced:boolean,now:number,syncStreak=0){const px=this.clamp(x),py=this.clamp(y),note=this.noteForPoint(track,px,py);this.taps.push({at:now,x:px,y:py});if(this.taps.length>16)this.taps.shift();this.state.averageTapX+=(px-this.state.averageTapX)*.22;this.state.averageTapY+=(py-this.state.averageTapY)*.22;this.melodyQueue.push({note,synced});if(this.melodyQueue.length>8)this.melodyQueue.shift();if(synced){this.state.melodyNotes.push(note);this.currentBarNotes.push(note);this.barMaxSync=Math.max(this.barMaxSync,syncStreak);this.state.totalSyncCount++;if(this.state.melodyNotes.length>8)this.state.melodyNotes.shift();}this.state.currentMelodyNote=note;return note;}
  recordContact(track:Track,x:number,y:number,synced:boolean,now:number,syncStreak=0){const note=this.noteForPoint(track,this.clamp(x),this.clamp(y));if(this.contactBuffer.length&&now-this.contactBuffer.at(-1)!.at>900)this.finalizeArpeggio();this.contactBuffer.push({note,at:now,synced});if(this.contactBuffer.length>=8)this.finalizeArpeggio();if(synced){this.state.arpeggioNotes.push(note);this.currentBarNotes.push(note);this.barMaxSync=Math.max(this.barMaxSync,syncStreak);this.state.totalSyncCount++;if(this.state.arpeggioNotes.length>8)this.state.arpeggioNotes.shift();}else if(this.state.arpeggioNotes.length<2)this.state.arpeggioNotes.push(note);return note;}
  onBar(bar:number){let remembered:MelodyMotif|undefined;const notes=this.currentBarNotes.slice(-8);if(this.barMaxSync>=3&&notes.length>=4&&new Set(notes).size>1&&!this.tooSimilar(notes)){const diversity=new Set(notes).size/notes.length,score=this.barMaxSync+diversity*3;remembered={notes:[...notes],score,createdBar:bar,uses:0};this.state.rememberedMotifs.push(remembered);this.state.rememberedMotifs.sort((a,b)=>b.score-a.score||b.createdBar-a.createdBar);this.state.rememberedMotifs=this.state.rememberedMotifs.slice(0,3);this.responses.push({bar:bar+1,notes:[...notes],variation:false},{bar:bar+2,notes:this.variation(notes),variation:true});this.state.selectedPrimaryMotif=[...this.state.rememberedMotifs[0].notes];this.state.selectedSecondaryMotif=[...(this.state.rememberedMotifs[1]?.notes??[])];}this.currentBarNotes=[];this.barMaxSync=0;this.responses=this.responses.filter(r=>r.bar>=bar);return remembered;}
  responseFor(bar:number,step:number){const response=this.responses.find(r=>r.bar===bar);if(!response||step>=response.notes.length)return undefined;return{note:response.notes[step],variation:response.variation};}
  consumeMelody(){const queued=this.melodyQueue.shift();if(queued){this.state.currentMelodyNote=queued.note;return queued;}if(this.state.melodyNotes.length){const note=this.state.melodyNotes[this.state.melodyCursor++%this.state.melodyNotes.length];this.state.currentMelodyNote=note;return{note,synced:false};}return undefined;}
  nextArpeggio(finale=false){const state=finale&&this.frozen?this.frozen:this.state,notes=finale&&state.finaleSnapshot?.primaryArpeggioMotif.length?state.finaleSnapshot.primaryArpeggioMotif:state.arpeggioMotifs[0]?.notes.length?state.arpeggioMotifs[0].notes:state.arpeggioNotes;if(!notes.length)return undefined;return notes[state.arpeggioCursor++%notes.length];}
  freeze(track:Track,nodes:Array<{x:number;y:number;note:number}>){this.finalizeArpeggio();const primary=this.state.rememberedMotifs[0]?.notes??this.state.melodyNotes.slice(-8);const fallback=primary.length>=4?primary:track.melody.slice(0,4);const arp=this.state.arpeggioMotifs[0]?.notes??this.state.arpeggioNotes;const snapshot:FinaleCompositionSnapshot={primaryMelodyMotif:[...fallback],secondaryMelodyMotif:this.state.rememberedMotifs[1]?.notes,primaryArpeggioMotif:[...(arp.length>=3?arp:track.arp)],tapDensity:this.state.tapDensity,averageTapY:this.state.averageTapY,averageTapX:this.state.averageTapX,hiHatDensity:this.state.hiHatDensity,kickVariation:this.state.kickVariation,snareTone:this.state.snareTone,longestSyncStreak:this.state.longestSyncStreak,totalSyncCount:this.state.totalSyncCount,nodePositions:nodes.map(n=>({...n}))};this.state.finaleSnapshot=snapshot;this.state.selectedPrimaryMotif=[...snapshot.primaryMelodyMotif];this.state.selectedSecondaryMotif=[...(snapshot.secondaryMelodyMotif??[])];this.frozen={...this.state,melodyNotes:[...this.state.melodyNotes],arpeggioNotes:[...this.state.arpeggioNotes],rememberedMotifs:this.state.rememberedMotifs.map(m=>({...m,notes:[...m.notes]})),arpeggioMotifs:this.state.arpeggioMotifs.map(m=>({...m,notes:[...m.notes]})),finaleSnapshot:snapshot};return snapshot;}
  setNextBeat(step:number){this.state.nextQuantizedBeat=step;}get playbackState(){return this.frozen??this.state;}
  setDebugMotif(notes:number[]){const motif={notes:[...notes],score:99,createdBar:0,uses:0};this.state.rememberedMotifs=[motif];this.state.selectedPrimaryMotif=[...notes];this.state.melodyNotes=[...notes];}
  private finalizeArpeggio(){const buffer=this.contactBuffer;if(buffer.length>=3&&buffer.some(x=>x.synced)&&new Set(buffer.map(x=>x.note)).size>=2){const motif={notes:buffer.map(x=>x.note).slice(-8),score:buffer.filter(x=>x.synced).length+new Set(buffer.map(x=>x.note)).size*.5,createdAt:buffer.at(-1)!.at};this.state.arpeggioMotifs.push(motif);this.state.arpeggioMotifs.sort((a,b)=>b.score-a.score||b.createdAt-a.createdAt);this.state.arpeggioMotifs=this.state.arpeggioMotifs.slice(0,3);}this.contactBuffer=[];}
  private tooSimilar(notes:number[]){const last=this.state.rememberedMotifs[0]?.notes;if(!last)return false;const len=Math.min(last.length,notes.length),same=notes.slice(0,len).filter((n,i)=>n===last[i]).length;return same/Math.max(notes.length,last.length)>.8;}
  private variation(notes:number[]){const varied=[...notes];if(varied.length>3){const last=varied.at(-1)!;varied[varied.length-1]=varied[0]===last?varied[1]:varied[0];}return varied;}
  private noteForPoint(track:Track,x:number,y:number){const ti=['LUMEN DRIVE','EMBER PULSE','AQUA BLOOM','VIOLET GRID','NOVA ASCENT'].indexOf(track.name),map=NOTE_MAPS[Math.max(0,ti)],bucket=Math.min(4,Math.floor(x*5)),octave=y<.33?12:y>.67?-12:0;return track.scale[map[bucket]%track.scale.length]+octave;}
  private clamp(v:number){return Math.max(0,Math.min(.999,v));}
  private createState():CompositionState{return{tapDensity:0,averageTapInterval:0,averageTapX:.5,averageTapY:.5,kickIntensity:0,kickVariation:0,snareTone:.5,snareFillLevel:0,hiHatDensity:0,hiHatOpenAmount:0,melodyNotes:[],melodyCursor:0,arpeggioNotes:[],arpeggioCursor:0,syncStreak:0,compositionEnergy:0,currentMelodyNote:0,nextQuantizedBeat:0,rememberedMotifs:[],arpeggioMotifs:[],longestSyncStreak:0,totalSyncCount:0,selectedPrimaryMotif:[],selectedSecondaryMotif:[]};}
}
