import './style.css';
import {AudioEngine} from './audio/AudioEngine';
import {TRACKS} from './audio/TrackDefinitions';
import {debugConfig,DEFAULTS} from './config/constants';
import {ResonanceEngine} from './game/ResonanceEngine';
import {FinaleController} from './game/FinaleController';
import {SessionController,type SessionPhase} from './game/SessionController';
import {Renderer} from './visual/Renderer';

const canvas=document.querySelector<HTMLCanvasElement>('#resonance')!,hint=document.querySelector<HTMLDivElement>('#hint')!,syncEl=document.querySelector<HTMLDivElement>('#sync')!,whiteout=document.querySelector<HTMLDivElement>('#whiteout')!;
const debugToggle=document.querySelector<HTMLButtonElement>('#debug-toggle')!,debugPanel=document.querySelector<HTMLElement>('#debug-panel')!,debugReadout=document.querySelector<HTMLOutputElement>('#debug-readout')!,forceFinale=document.querySelector<HTMLButtonElement>('#force-finale')!;
const cfg=debugConfig(),audio=new AudioEngine(cfg.syncWindow),engine=new ResonanceEngine(cfg.threshold,cfg.initialEnergy,cfg),finale=new FinaleController(engine,cfg.finaleSteps),session=new SessionController(cfg),renderer=new Renderer(canvas,cfg);
let trackIndex=cfg.track,track=TRACKS[trackIndex],finaleDuration=0,last=performance.now(),syncTimer=0,finaleStarted=false,forceFinaleRequested=false;
document.documentElement.style.background=track.colors.bg;

function showMoment(label:string,duration=500){syncEl.textContent=label;syncEl.classList.add('show');clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>syncEl.classList.remove('show'),duration);}
function judge(){const{accuracy,beat}=audio.beatAccuracy(),result=engine.sync.judge(accuracy,beat,performance.now());if(result.synced)showMoment(result.label,360);return result;}
function advanceTrackIfNeeded(){if(!finaleStarted)return;trackIndex=(trackIndex+1)%TRACKS.length;track=TRACKS[trackIndex];finaleStarted=false;document.documentElement.style.background=track.colors.bg;}
async function begin(){await audio.init();engine.begin();audio.start(track);session.begin(performance.now());forceFinaleRequested=false;hint.style.opacity='0';finaleStarted=false;whiteout.classList.remove('show');}
async function input(x:number,y:number){if(engine.state==='idle'||engine.state==='rebirth'){advanceTrackIfNeeded();await begin();x=renderer.w/2;y=renderer.h/2;}if(engine.state!=='active'){engine.burst(x,y,3,.5);return;}const point=renderer.screenToWorld(x,y),result=judge(),note=audio.composeTap(point.x/renderer.w,point.y/renderer.h,result.synced,result.streak);engine.tap(point.x,point.y,result,note);audio.tapFeedback(result.synced?result.accuracy:0,note);if(result.synced)renderer.focus(point.x,point.y,result.accuracy);}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();void input(e.clientX-r.left,e.clientY-r.top);},{passive:false});
window.addEventListener('resize',renderer.resize);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&audio.ctx?.state==='suspended')void audio.ctx.resume();});
audio.onBeat=event=>renderer.beat(event);audio.onMemory=motif=>{showMoment('MEMORY',750);renderer.memory(motif.notes);};

function startPrelude(now:number){session.startPrelude(now);engine.state='prelude';const motif=audio.composition.state.selectedPrimaryMotif.length?audio.composition.state.selectedPrimaryMotif:audio.composition.state.melodyNotes;if(motif.length)renderer.memory(motif);}
function startFinale(now:number){finaleStarted=true;engine.state='active';finaleDuration=finale.start(now,Math.min(160,audio.bpm+16));audio.enterFinale(engine.nodes.map(n=>({x:n.x,y:n.y,note:n.note})));audio.fadeAfter((650+finaleDuration+DEFAULTS.whiteHoldMs)/1000,DEFAULTS.fadeMs/1000);}
function requirements(){const c=audio.composition.state;return{energy:engine.energy,threshold:engine.threshold,nodeCount:engine.nodes.length,melodyCount:c.melodyNotes.length,arpeggioCount:c.arpeggioNotes.length,motifCount:c.rememberedMotifs.length};}
function loop(now:number){const dt=Math.min(34,now-last);last=now;if(engine.state==='active'||engine.state==='prelude'||engine.state==='finale')audio.setProgress(engine.progress);audio.updateComposition(now,dt,engine.sync.streak);engine.update(now,dt,judge,(result,index)=>{const n=engine.nodes[index];if(n)audio.composeContact(n.x/renderer.w,n.y/renderer.h,result.synced,result.streak);audio.resonate(result.synced?result.accuracy:0,index);if(result.synced){showMoment(result.label,360);if(n)renderer.focus(n.x,n.y,result.accuracy);}});const progress=session.update(now,requirements());if(engine.state==='active'&&(progress.shouldPrelude||forceFinaleRequested))startPrelude(now);if(engine.state==='prelude'&&(progress.shouldFinale||forceFinaleRequested))startFinale(now);finale.update(now,finaleDuration);whiteout.classList.toggle('show',engine.state==='whiteout');if(engine.state==='silence')audio.stop();if(engine.state==='rebirth'){hint.textContent='中央の光をタップ';hint.style.opacity='1';}if(engine.state==='idle'&&finaleStarted)advanceTrackIfNeeded();renderer.draw(now,engine,track);if(cfg.debug)renderDebug(now);requestAnimationFrame(loop);}
function renderDebug(now:number){const c=audio.composition.state,snapshot=c.finaleSnapshot;debugReadout.textContent=`${engine.state} · phase ${session.phase} · ${track.name}\nelapsed ${Math.round((now-session.startedAt)/1000)}s / expected ${Math.round(session.expectedDuration/1000)}s\nenergy ${Math.round(engine.energy)}/${engine.threshold} · canFinale ${session.canStartFinale}\nmelody [${c.melodyNotes.join(', ')}]\nmotifs ${c.rememberedMotifs.map(m=>`[${m.notes.join(',')}]`).join(' ')}\nprimary [${c.selectedPrimaryMotif.join(',')}] · secondary [${c.selectedSecondaryMotif.join(',')}]\narp [${c.arpeggioNotes.join(',')}] · arpMotifs ${c.arpeggioMotifs.length}\nSYNC ${c.syncStreak} · longest ${c.longestSyncStreak} · total ${c.totalSyncCount}\nnext beat ${c.nextQuantizedBeat} · next response ~${Math.round(session.nextCallResponseTime)}ms\nfinale round ${audio.currentFinaleRound} · voices ${audio.currentVoiceCount}\nsnapshot ${snapshot?`M${snapshot.primaryMelodyMotif.length}/A${snapshot.primaryArpeggioMotif.length}/D${snapshot.tapDensity.toFixed(1)}`:'—'}`;}
function debugButton(label:string,action:()=>void){const button=document.createElement('button');button.textContent=label;button.addEventListener('click',action);debugPanel.append(button);}
if(cfg.debug){debugToggle.hidden=false;debugToggle.onclick=()=>debugPanel.hidden=!debugPanel.hidden;forceFinale.onclick=()=>{if(engine.state==='active'||engine.state==='prelude')forceFinaleRequested=true;};for(const phase of['A','B','C']as SessionPhase[])debugButton(`PHASE ${phase}`,()=>session.forcePhase(phase,performance.now()));debugButton('PHASE D',()=>{if(engine.state==='active')startPrelude(performance.now());});debugButton('FINALE ROUND 1',()=>audio.debugFinaleRound(1));debugButton('FINALE ROUND 2',()=>audio.debugFinaleRound(2));debugButton('SET MOTIF',()=>{audio.composition.setDebugMotif(track.melody.slice(0,4));renderer.memory(track.melody.slice(0,4));});debugButton('WHITEOUT SOON',()=>{if(engine.state==='finale')engine.finaleStart=performance.now()-finaleDuration-400;});}
requestAnimationFrame(loop);
